// Generated by gencpp from file submarinedrone/depth_warning.msg
// DO NOT EDIT!


#ifndef SUBMARINEDRONE_MESSAGE_DEPTH_WARNING_H
#define SUBMARINEDRONE_MESSAGE_DEPTH_WARNING_H

#include <ros/service_traits.h>


#include <submarinedrone/depth_warningRequest.h>
#include <submarinedrone/depth_warningResponse.h>


namespace submarinedrone
{

struct depth_warning
{

typedef depth_warningRequest Request;
typedef depth_warningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct depth_warning
} // namespace submarinedrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::submarinedrone::depth_warning > {
  static const char* value()
  {
    return "22367e279ad9f68e7619b633d4d05ec2";
  }

  static const char* value(const ::submarinedrone::depth_warning&) { return value(); }
};

template<>
struct DataType< ::submarinedrone::depth_warning > {
  static const char* value()
  {
    return "submarinedrone/depth_warning";
  }

  static const char* value(const ::submarinedrone::depth_warning&) { return value(); }
};


// service_traits::MD5Sum< ::submarinedrone::depth_warningRequest> should match
// service_traits::MD5Sum< ::submarinedrone::depth_warning >
template<>
struct MD5Sum< ::submarinedrone::depth_warningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::submarinedrone::depth_warning >::value();
  }
  static const char* value(const ::submarinedrone::depth_warningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::submarinedrone::depth_warningRequest> should match
// service_traits::DataType< ::submarinedrone::depth_warning >
template<>
struct DataType< ::submarinedrone::depth_warningRequest>
{
  static const char* value()
  {
    return DataType< ::submarinedrone::depth_warning >::value();
  }
  static const char* value(const ::submarinedrone::depth_warningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::submarinedrone::depth_warningResponse> should match
// service_traits::MD5Sum< ::submarinedrone::depth_warning >
template<>
struct MD5Sum< ::submarinedrone::depth_warningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::submarinedrone::depth_warning >::value();
  }
  static const char* value(const ::submarinedrone::depth_warningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::submarinedrone::depth_warningResponse> should match
// service_traits::DataType< ::submarinedrone::depth_warning >
template<>
struct DataType< ::submarinedrone::depth_warningResponse>
{
  static const char* value()
  {
    return DataType< ::submarinedrone::depth_warning >::value();
  }
  static const char* value(const ::submarinedrone::depth_warningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBMARINEDRONE_MESSAGE_DEPTH_WARNING_H
