// Generated by gencpp from file mydrone/alt_warning.msg
// DO NOT EDIT!


#ifndef MYDRONE_MESSAGE_ALT_WARNING_H
#define MYDRONE_MESSAGE_ALT_WARNING_H

#include <ros/service_traits.h>


#include <mydrone/alt_warningRequest.h>
#include <mydrone/alt_warningResponse.h>


namespace mydrone
{

struct alt_warning
{

typedef alt_warningRequest Request;
typedef alt_warningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct alt_warning
} // namespace mydrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mydrone::alt_warning > {
  static const char* value()
  {
    return "22367e279ad9f68e7619b633d4d05ec2";
  }

  static const char* value(const ::mydrone::alt_warning&) { return value(); }
};

template<>
struct DataType< ::mydrone::alt_warning > {
  static const char* value()
  {
    return "mydrone/alt_warning";
  }

  static const char* value(const ::mydrone::alt_warning&) { return value(); }
};


// service_traits::MD5Sum< ::mydrone::alt_warningRequest> should match
// service_traits::MD5Sum< ::mydrone::alt_warning >
template<>
struct MD5Sum< ::mydrone::alt_warningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mydrone::alt_warning >::value();
  }
  static const char* value(const ::mydrone::alt_warningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mydrone::alt_warningRequest> should match
// service_traits::DataType< ::mydrone::alt_warning >
template<>
struct DataType< ::mydrone::alt_warningRequest>
{
  static const char* value()
  {
    return DataType< ::mydrone::alt_warning >::value();
  }
  static const char* value(const ::mydrone::alt_warningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mydrone::alt_warningResponse> should match
// service_traits::MD5Sum< ::mydrone::alt_warning >
template<>
struct MD5Sum< ::mydrone::alt_warningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mydrone::alt_warning >::value();
  }
  static const char* value(const ::mydrone::alt_warningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mydrone::alt_warningResponse> should match
// service_traits::DataType< ::mydrone::alt_warning >
template<>
struct DataType< ::mydrone::alt_warningResponse>
{
  static const char* value()
  {
    return DataType< ::mydrone::alt_warning >::value();
  }
  static const char* value(const ::mydrone::alt_warningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYDRONE_MESSAGE_ALT_WARNING_H
